@Library('jenkins_shared_lib') _

pipeline {
    agent {
        label 'k3s'
    }
    options {
        skipDefaultCheckout();
        timestamps();
        ansiColor('xterm')
    }
    environment {
        DEFAULT_BRANCH = 'master'
        CREDITS_ID = 'github-token'
    }
    stages {
        stage('Init ENV') {
            steps {
                script {
                    initEnv()
                }
            }
        }

        stage('Configure Triggers') {
            steps {
                script {
                    configureTriggers()
                }
            }
        }

        stage('Checkout') {
            parallel {
                stage('Checkout PR') {
                    when { expression { isPullRequestBuild() } }
                    steps {
                         checkoutPullRequest()
                    }
                }

                stage('Checkout Manual') {
                    when { not { expression { isPullRequestBuild() } } }
                    steps {
                        checkoutBranch("*/${env.DEFAULT_BRANCH}")
                    }
                }
            }
        }

        stage('Init') {
            parallel {
                stage('Init Pipeline Status') {
                    when { expression { isPullRequestBuild() } }
                    steps {
                        script {
                            githubWebhook('PENDING', 'Pipeline started')
                        }
                    }
                }

                stage('Init Submodules') {
                    steps {
                        script {
                            initSubmodules()
                        }
                    }
                }

                stage('Init K3s config') {
                    steps {
                        script {
                            configureK3s()
                        }
                    }
                }
            }
        }

        stage('Copy Config') {
            steps {
                script {
                    if (fileExists('config')) {
                        sh '''
                            mkdir -p ./helm/config && cp -r config/* ./helm/config/
                        '''
                    }
                }
            }
        }

        stage('Test Lint') {
            steps {
                script {
                    sh '''
                        helm lint ./helm -f config.yml
                        helm template ./helm -f config.yml
                    '''
                }
            }
        }
        stage('Dry Run Test') {
            steps {
                script {
                    sh '''
                        helm upgrade --install hello-world ./helm \
                            -f config.yml \
                            --kubeconfig kubeconfig.yaml \
                            --dry-run --debug
                    '''
                }
            }
        }
    }
    post {
        success {
            script {
                githubWebhook('SUCCESS', 'All stages passed ✅')
            }
        }
        failure {
            script {
                githubWebhook('FAILURE', 'Pipeline failed ❌')
            }
        }
    }
}